core/urls.py
from django.contrib import admin
from django.urls import (path,
                         include)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('users.urls')),
    path("quiz/", include('quiz.urls')),
]

quiz/urls.py
from django.urls import path
from quiz import views

app_name = 'quiz'

urlpatterns = [
    path('', views.index, name='index'),
    path('start/<int:quiz_id>/', views.start_quiz, name='start'),
    path('question/<int:quiz_id>/<int:question_id>/', views.question, name='question'),
    path('result/<int:quiz_id>/', views.result, name='result')
]

users/urls.py
from django.urls import path

from users.views import (LogIn,
                         SignUp,
                         user_logout)

urlpatterns = [
    path('', LogIn.as_view(), name='login'),
    path('logout/', user_logout, name='logout'),
    path('signup/', SignUp.as_view(), name='signup'),
]

quiz/models.py
from django.db import models
from django.contrib.auth.models import User


class Quiz(models.Model):
    title = models.CharField(max_length=256)
    category = models.CharField(max_length=256)

    def __str__(self):
        return self.title


class Question(models.Model):
    text = models.CharField(max_length=512)

    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    def get_next_question(self):
        next_question = Question.objects.filter(quiz=self.quiz, pk__gt=self.pk).first()
        return next_question

    def __str__(self):
        return self.text


class Choice(models.Model):
    text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class QuizTaker(models.Model):
    completed = models.BooleanField(default=False)
    correct_answers = models.IntegerField(default=0)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    current_question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'{self.user.username} - {self.quiz.title}'

users/models.py
from django.db import models

# Create your models here.

quiz/forms.py
from django import forms
from quiz.models import Quiz


class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ['title']

quiz/views.py
from django.shortcuts import (render,
                              redirect,
                              get_object_or_404)
from django.contrib.auth.decorators import login_required

from quiz.models import (Quiz,
                         Question,
                         Choice,
                         QuizTaker)


def index(request):
    quizzes = Quiz.objects.all()

    context = {'quizzes': quizzes, 'categories': list(set([quiz.category for quiz in quizzes]))}

    return render(request=request, template_name='quiz/index.html', context=context)


@login_required
def start_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    quiz_taker, created = QuizTaker.objects.get_or_create(user=request.user, quiz=quiz)

    if quiz_taker.completed:
        return redirect(to='quiz:result', quiz_id=quiz_id)

    if quiz_taker.current_question:
        return redirect(to='quiz:question', quiz_id=quiz_id, question_id=quiz_taker.current_question.pk)
    else:
        first_question = quiz.question_set.first()
        if first_question:
            quiz_taker.current_question = first_question
            quiz_taker.save()
            return redirect(to='quiz:question', quiz_id=quiz_id, question_id=first_question.pk)
        else:
            return redirect(to='quiz:result', quiz_id=quiz_id)


@login_required
def question(request, quiz_id, question_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    question = get_object_or_404(Question, pk=question_id)
    quiz_taker = get_object_or_404(QuizTaker, user=request.user, quiz=quiz)

    if request.method == 'POST':
        selected_choices = request.POST.getlist('choice[]')
        if len(selected_choices) > 0:
            is_correct = True
            for selected_choice in selected_choices:
                choice = get_object_or_404(Choice, pk=selected_choice)
                if not choice.is_correct:
                    is_correct = False

            next_question = question.get_next_question()
            quiz_taker.current_question = next_question

            if is_correct:
                quiz_taker.correct_answers += 1

            quiz_taker.save()

            if next_question:
                return redirect('quiz:question', quiz_id=quiz_id, question_id=next_question.pk)
            else:
                quiz_taker.completed = True
                quiz_taker.save()
                return redirect('quiz:result', quiz_id=quiz_id)

    if question != quiz_taker.current_question:
        if quiz_taker.current_question:
            return redirect('quiz:question', quiz_id=quiz_id, question_id=quiz_taker.current_question.pk)
        else:
            return redirect('quiz:start', quiz_id=quiz_id)

    context = {'quiz': quiz, 'question': question}

    return render(request=request, template_name='quiz/question.html', context=context)


@login_required
def result(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    quiz_taker = get_object_or_404(QuizTaker, user=request.user, quiz=quiz)

    correct_answers = quiz_taker.correct_answers
    total_questions = quiz.question_set.count()
    percentage = (correct_answers / total_questions) * 100

    context = {
        'quiz': quiz,
        'correct_answers': correct_answers,
        'not_correct_answers': total_questions - correct_answers,
        'percentage': percentage
    }

    return render(request=request, template_name='quiz/result.html', context=context)

users/views.py
from django.contrib.auth import (login,
                                 logout,
                                 authenticate)
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import CreateView


class LogIn(LoginView):
    template_name = 'index.html'

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')
        rememberme = request.POST.get('rememberme')

        user_obj = User.objects.filter(username=username).first()
        if user_obj is None:
            messages.success(request=request, message='User is not found!')
            return redirect('login')

        user = authenticate(username=username, password=password)
        if user is None:
            messages.success(request=request, message='Wrong password entered!')
            return redirect('login')

        login(request=request, user=user)

        if not rememberme:
            self.request.session.set_expiry(0)
            self.request.session.modified = True

        messages.success(request=request, message='Success')

        return redirect('quiz/')


class SignUp(CreateView):
    model = User
    fields = '__all__'
    template_name = 'register.html'
    success_url = reverse_lazy('login')

    def post(self, request, *args, **kwargs):
        try:
            password1 = request.POST.get('password1')
            password2 = request.POST.get('password2')
            username = request.POST.get('username')
            email = request.POST.get('email')
            first_name = request.POST.get('firstname')
            last_name = request.POST.get('lastname')

            if password1 != password2:
                messages.success(request, 'Passwords in both password fields do not match!')
                return redirect('signup')

            if User.objects.filter(username=username).first():
                messages.success(request, 'This user is already registered!')
                return redirect('signup')

            if User.objects.filter(email=email).first():
                messages.success(request, 'This email is already registered!')
                return redirect('signup')

            user_obj = User.objects.create(
                username=username,
                email=email,
                first_name=first_name,
                last_name=last_name
            )
            user_obj.set_password(raw_password=password1)
            user_obj.save()
            return redirect('login')
        except Exception as e:
            messages.error(request, f'Error {e}')
            return redirect('signup')


def user_logout(request):
    logout(request)
    return redirect(to='login')

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign In</title>
</head>

<body>
<h1>Log In</h1>
{% if messages %}
    {% for message in messages %}
        {{ message }}
    {% endfor %}
{% endif %}

<form action="{% url 'login' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username" required><br>
    <input type="password" name="password" placeholder="Password" required><br>
    <input type="submit" value="LogIn">
</form>

<br>
<a href="{% url 'signup' %}">Sign Up</a>
</body>
</html>

templates/quiz/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Quiz platform</title>
</head>
<body>
{% if user.is_authenticated %}
    <p>Hi, {{ user.username }}! <a href="{% url 'logout' %}">Exit</a></p>
{% else %}
    <p><a href="{% url 'login' %}">Log In</a></p>
{% endif %}
{% block content %}
{% endblock %}
</body>
</html>

templates/quiz/index.html
{% extends 'quiz/base.html' %}

{% block content %}
    <h1>Список тестов</h1>
    <hr>
    {% for category in categories %}
        <h4>{{ category }}</h4>
        <ul>
            {% for quiz in quizzes %}
                {% if quiz.category == category %}
                    <li><a href="{% url 'quiz:start' quiz.id %}">{{ quiz.title }}</a></li>
                {% endif %}
            {% endfor %}
        </ul>
        <hr>
    {% endfor %}
{% endblock %}

templates/quiz/question.html
{% extends 'quiz/base.html' %}

{% block content %}
    <h1>{{ quiz.title }}</h1>

    <hr>

    <p>Question: {{ question.text }}</p>

    <hr>

    <form action="{% url 'quiz:question' quiz.id question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="checkbox" id="{{ choice.id }}" name="choice[]" value="{{ choice.id }}">
            <label for="{{ choice.id }}">{{ choice.text }}</label><br>
        {% endfor %}
        <hr>
        <button type="submit">Submit</button>
    </form>
{% endblock %}

templates/quiz/result.html
{% extends 'quiz/base.html' %}

{% block content %}
     <h1>Results</h1>
     <p>Test: {{ quiz.title }}</p>
     <p>Number of correct answers: {{ correct_answers }}</p>
     <p>Number of incorrect answers: {{ not_correct_answers }}</p>
     <p>Percentage of correct answers: {{ percentage }}%</p>

    <button><a href="../../">Back to the list of quizzes</a></button>
{% endblock %}

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up</title>
</head>

<body>
<h1>Sign Up</h1>
{% if messages %}
    {% for message in messages %}
        {{ message }}<br>
    {% endfor %}
{% endif %}

<form action="{% url 'signup' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username" required style="height: 30px; width: 200px"><br>
    <input type="text" name="firstname" placeholder="First Name" required style="height: 30px; width: 200px"><br>
    <input type="text" name="lastname" placeholder="Last Name" required style="height: 30px; width: 200px"><br>
    <input type="email" name="email" placeholder="Email" required style="height: 30px; width: 200px"><br>
    <input type="password" name="password1" placeholder="Password" required style="height: 30px; width: 200px"><br>
    <input type="password" name="password2" placeholder="Password confirm" required style="height: 30px; width: 200px"><br>
    <input type="submit" value="Sign Up"><br>
</form>
</body>
</html>